FROM node:20-alpine

ARG NUXT_PUBLIC_APP_NAME
ARG NUXT_NODE_ENV
ARG NUXT_PUBLIC_WEB_BASE
ARG NUXT_PUBLIC_WEB_PATH
ARG NUXT_PUBLIC_API_BASE
ARG NUXT_PUBLIC_API_PATH
ARG NUXT_PUBLIC_GRAPHQL_PATH
ARG NUXT_PUBLIC_AZURE_AD_CLIENT_ID
ARG NUXT_PUBLIC_AZURE_AD_AUTHORITY
ARG NUXT_PUBLIC_AZURE_AD_SCOPES



ENV NUXT_PUBLIC_APP_NAME=$NUXT_PUBLIC_APP_NAME
ENV NUXT_NODE_ENV=$NUXT_NODE_ENV
ENV NUXT_PUBLIC_WEB_BASE=$NUXT_PUBLIC_WEB_BASE
ENV NUXT_PUBLIC_WEB_PATH=$NUXT_PUBLIC_WEB_PATH
ENV NUXT_PUBLIC_API_BASE=$NUXT_PUBLIC_API_BASE
ENV NUXT_PUBLIC_API_PATH=$NUXT_PUBLIC_API_PATH
ENV NUXT_PUBLIC_GRAPHQL_PATH=$NUXT_PUBLIC_GRAPHQL_PATH
ENV NUXT_PUBLIC_AZURE_AD_CLIENT_ID=$NUXT_PUBLIC_AZURE_AD_CLIENT_ID
ENV NUXT_PUBLIC_AZURE_AD_AUTHORITY=$NUXT_PUBLIC_AZURE_AD_AUTHORITY
ENV NUXT_PUBLIC_AZURE_AD_SCOPES=$NUXT_PUBLIC_AZURE_AD_SCOPES


ENV TZ=Asia/Bangkok

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN mkdir -p /app
COPY . /app/

WORKDIR /app
RUN yarn
RUN yarn build

EXPOSE 3000

CMD [ "yarn", "start" ]